version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.4.3-hadoop2.7
    command: /spark/sbin/../bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - spark-network

  spark-worker:
    image: bde2020/spark-master:2.4.3-hadoop2.7
    command: /spark/sbin/../bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      PYSPARK_PYTHON: python3
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
      - 8081
    networks:
      - spark-network

  spark-driver:
    image: bde2020/spark-master:2.4.3-hadoop2.7
    command: bash
    hostname: spark-driver
    stdin_open: true
    tty: true
    environment:
      PYSPARK_PYTHON: python3
    links:
      - spark-master
    ports:
      - 8088:8088
      - 8042:8042
      - 4041:4040
    networks:
      - spark-network
networks: 
  spark-network:
